version: 0.2.{build}-{branch}

image: Visual Studio 2015

environment:

  matrix:

    - PYTHON_VERSION: 3.8
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

    - PYTHON_VERSION: 3.9
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

matrix:

  allow_failures:

    - PYTHON_VERSION: 3.9
      PYTHON_ARCH: x64
      MINICONDA: C:\Miniconda37-x64

install:
  - set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%

  # Install the build and runtime dependencies of the project.
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -q -n test-environment python=%PYTHON_VERSION%
  - activate test-environment
  - python --version

  - conda install appdirs bidict cartopy gdal matplotlib-base numpy psutil pyproj
  - pip install coveralls PySide6 pytest pytest-cov PyYAML wheel

build: off
build_script:
  - pip install -e .
  - conda list --show-channel-urls

test: off
test_script:
  - py.test --cov
  - coverage report -m
  - coveralls

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*
